<div id="login-box" class="login-box visible widget-box no-border">
  <div class="widget-body">
    <div class="widget-main">
      <h4 class="header blue lighter bigger">
        <i class="ace-icon fa fa-coffee green"></i>
        Ingrese su información
      </h4>

      <div class="space-6"></div>

      <?php echo Form::open() ?>
        <fieldset>
          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <?php echo Form::text("login", "class='form-control' placeholder='Nombre de usuario'") ?>
              <i class="ace-icon fa fa-user"></i>
            </span>
          </label>

          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <?php echo Form::pass("password", "class='form-control' placeholder='Contraseña'") ?>
              <i class="ace-icon fa fa-lock"></i>
            </span>
          </label>

          <div class="space"></div>

          <div class="clearfix">
            <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
              <i class="ace-icon fa fa-key"></i>
              <span class="bigger-110">Iniciar</span>
            </button>
          </div>

          <div class="space-4"></div>
        </fieldset>
      <?php echo Form::close() ?>
    </div><!-- /.widget-main -->

    <div class="toolbar clearfix">
      <div>
        <a href="#" data-target="#forgot-box" class="forgot-password-link">
          <i class="ace-icon fa fa-arrow-left"></i>
          Olvide mi contraseña
        </a>
      </div>

      <div>
        <a href="<?php echo PUBLIC_PATH ?>auth/registrarme" data-target="#signup-box" class="user-signup-link">
          Quiero registrarme
          <i class="ace-icon fa fa-arrow-right"></i>
        </a>
      </div>
    </div>
  </div><!-- /.widget-body -->
</div><!-- /.login-box -->