<div id="signup-box" class="signup-box visible widget-box no-border">
  <div class="widget-body">
    <div class="widget-main">
      <h4 class="header green lighter bigger">
        <i class="ace-icon fa fa-users blue"></i>
        Nuevo usuario
      </h4>

      <div class="space-6"></div>
      <p> Ingrese la siguiente información: </p>

      <?php echo Form::open() ?>
        <fieldset>
          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <input type="text" name="userName" id="userName" class="form-control" placeholder="Username"  required/>
              <i class="ace-icon fa fa-user"></i>
            </span>
          </label>

          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <input type="password" name="password" id="password" class="form-control" placeholder="Password"  required/>
              <i class="ace-icon fa fa-lock"></i>
            </span>
          </label>

          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <input type="password" name="repassword" id="repassword" class="form-control" placeholder="Repeat password" required/>
              <i class="ace-icon fa fa-retweet"></i>
            </span>
          </label>

          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <input type="number" name="edad" id="edad" class="form-control" placeholder="Edad" min="18" required/>
              <i class="ace-icon fa fa-retweet"></i>
            </span>
          </label>

          <label class="block clearfix">
            <span class="block input-icon input-icon-right">
              <input type="phone" name="phone-number" id="phone-number" class="form-control" placeholder="Teléfono"  required/>
              <i class="ace-icon fa fa-retweet"></i>
            </span>
          </label>

          <label class="block">
            <input type="checkbox" class="ace" required />
            <span class="lbl">
              Acepto los 
              <a href="#">terminos de usuario</a>
            </span>
          </label>

          <div class="space-24"></div>

          <div class="clearfix">
            <button type="reset" class="width-30 pull-left btn btn-sm">
              <i class="ace-icon fa fa-refresh"></i>
              <span class="bigger-110">Limpiar</span>
            </button>

            <button type="submit" class="width-65 pull-right btn btn-sm btn-success">
              <span class="bigger-110">Registrar</span>

              <i class="ace-icon fa fa-arrow-right icon-on-right"></i>
            </button>
          </div>
        </fieldset>
        <?php View::content(); ?>
      <?php echo Form::close() ?>
    </div>

    <div class="toolbar center">
      <a href="<?php echo PUBLIC_PATH ?>auth/login" data-target="#login-box" class="back-to-login-link">
        <i class="ace-icon fa fa-arrow-left"></i>
        Iniciar sesión
      </a>
    </div>
  </div><!-- /.widget-body -->
</div><!-- /.signup-box -->
