<?php echo Form::open(null, 'POST', "class='form-horizontal' role='form'") ?>
  <?php echo Form::hidden('impuestos.id') ?>
  <div class="form-group">
    <label for="codigo" class="col-sm-3 control-label no-padding-right">Codigo</label>
    <div class="col-sm-9">
      <?php echo Form::text('impuestos.codigo', "class='col-xs-10 col-sm-5 control-form' readonly") ?>
    </div>
  </div>
  <div class="form-group">
    <label for="descripcion" class="col-sm-3 control-label no-padding-right">Descripcion</label>
    <div class="col-sm-9">
      <?php echo Form::text('impuestos.descripcion', "class='col-xs-10 col-sm-5 control-form' readonly") ?>
    </div>
  </div>
  <div class="form-group">
    <label for="porcentaje" class="col-sm-3 control-label no-padding-right">Porcentaje</label>
    <div class="col-sm-9">
      <?php echo Form::number('impuestos.porcentaje', "class='col-xs-10 col-sm-5' step='0.01 control-form' readonly") ?>
    </div>
  </div>
  <div class="form-group">
    <label for="cuenta" class="col-sm-3 control-label no-padding-right">cuenta</label>
    <div class="col-sm-9">
      <?php echo Form::text('impuestos.cuenta', "class='col-xs-10 col-sm-5 control-form' readonly") ?>
    </div>
  </div>
<?php echo Form::close() ?>